f= open("output.txt",'w')
a=input("Enter what you wish to in the file: ")
w=f.write(a)
f.close()
f= open("output.txt",'a')
e=input("Enter anything that you wish to append to the file: ")
x=f.write(e)
f.close()
f= open("output.txt",'r')
print("Final content of the file: ")
r=f.read()
print(r)
f.close()